services:
  postgres_db:
      image: postgres:latest
      environment:   
        db_password: ${db_password}
        db_database: ${db_database}
        db_user: ${db_user}
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      networks:
        - rasp
  rasp:
      build: .
      depends_on:
        - postgres_db
      environment:
        db_user: ${db_user}
        db_password: ${db_password}
        db_host: ${db_host}
        db_port: ${db_port}
        db_database: ${db_database}
      networks:
        - rasp
  
networks:
  rasp:
    driver: bridge
