DROP TABLE IF EXISTS m2m_groups_lessons;

DROP TABLE IF EXISTS lessons;

DROP TABLE IF EXISTS lesson_time;

DROP TABLE IF EXISTS rooms;

DROP TABLE IF EXISTS buildings;

DROP TABLE IF EXISTS teachers;

DROP TABLE IF EXISTS groups;

DROP TABLE IF EXISTS faculties;

DROP TABLE IF EXISTS education_types;

DROP TABLE IF EXISTS departments;
